### ISSUE TITLE
more fastq file

### ISSUE THREAD

**Issue by Jwindler** [JiaoLaboratory/CRAQ#11]
How should I run `CRAQ` if I have multiple sms or ngs input data？ @JiaoLaboratory

**Comment by JiaoLaboratory** [comment]
Sorry for my delay reply for my busy,

CRAQ does not support multiple reads input now; Users can multiple reads fastq together (use  cat (zcat) ) , or merge bam file together (merged.bam); 

following:
(for SMS ) : 
 zcat SMS_smaple1.fa.gz SMS_smaple2.fa.gz >SMS.fa.gz  
 or
 samtools merge SMS.fa.merged.bam SMS_smaple1.fa.bam SMS_smaple2.fa.bam

(for NGS):  
zcat NGS_smaple1_R1.fa.gz NGS_smaple2_R1.fa.gz >NGS_R1.fa.gz
zcat NGS_smaple1_R2.fa.gz NGS_smaple2_R2.fa.gz >NGS_R2.fa.gz
or 
samtools merge NGS.fa.merged.bam NGS_smaple1.fa.bam NGS_smaple2.fa.bam

and perform:
craq  -g  assembly.fa -sms SMS.fa.gz -ngs NGS_R1.fa.gz,NGS_R2.fa.gz
or
craq  -g  assembly.fa -sms  SMS.fa.merged.bam -ngs NGS_R1.fa.gz,NGS_R2.fa.gz
....

I will update this requirement later, but it will take some time for my busy recently.
