### ISSUE TITLE
Do you need to perform genome masking prior to CRAQ?

### ISSUE THREAD

**Issue by Isoris** [JiaoLaboratory/CRAQ#15]
Hi, thanks for the tool, 

Do you recommend to mask repetitive elements before running CRAQ or not?

Thank you for the answer, Quen

**Comment by JiaoLaboratory** [comment]
Masking repete unnecessary and unreasonable. 
Masking turns repeat sequences into N, which  forces some sequences to align to other regions, leading to false positives

**Comment by Isoris** [comment]
Ok thanks!
