### ISSUE TITLE
How can rerun only the plotting part?

### ISSUE THREAD

**Issue by Bank-tidy** [JiaoLaboratory/CRAQ#16]
I encountered an issue while running a command with CRAQ software. The command I used was:

- code:

`{softdir}/craq -g ${qry_genome} -sms ${TGS_bam} -D ${output} -t 60 -pl T`

However, I received an error message indicating a problem with a missing numpy module:

- error:

```
Traceback (most recent call last):
  File "software/apps/CRAQ/src/CRAQcircos.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "local/lib/python3.11/site-packages/matplotlib/__init__.py", line 156, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```
It seems my Python environment lacks the numpy library. My program has already completed its execution. After installing numpy, how can I rerun only the plotting part of my program?

Thank you for your assistance!

**Comment by JiaoLaboratory** [comment]
if you have finished CRAQ and want to do ploting only,  you could follow as: 

##step1: Get user-specified regional(i.e. window=10000) AQI score.

cat locER_out/out_final.CRE.bed strER_out/out_final.CSE.bed >CRE_CSE.bed
perl CRAQ/src/regional_AQI.pl ../seq.size 10000 10000 CRE_CSE.bed >w10k_AQI.out

##step2: plot AQI score.

python CRAQ/src/CRAQcircos.py --genome_size ../seq.size --genome_error_loc CRE_CSE.bed --genome_score w10k_AQI.out --output w10k_AQI.out.pdf

**Comment by Bank-tidy** [comment]
Thanks for your suggestion, the pdf has been generated successfully！
