### ISSUE TITLE
How is the average AQI calculated?

### ISSUE THREAD

**Issue by jolbi** [JiaoLaboratory/CRAQ#25]
Hi, thank you for the great tool. I ran the pipeline with a genome containing multiple haplotypes. I want to calculate the average AQI for each haplotype subassembly without rerunning the whole pipeline.

How is the average AQI of the whole genome calculated? I can't find this information in the paper. I am sorry if I missed it.
Thank you in advance.
Tim

**Comment by JiaoLaboratory** [comment]
I get your idea. sorry for that I have not been work these days & I will reply with a solution to you within recent days. Thank you for your using of CRAQ.

**Comment by jolbi** [comment]
Thank you very much for your fast response. I ran the script and it works as expected. I have the results I needed.
